prefix = /usr/local
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
datarootdir = $(prefix)/share
datadir = $(datarootdir)
sysconfdir = $(prefix)/etc
sharedstatedir = $(prefix)/com
localstatedir = $(prefix)/var
includedir = $(prefix)/include
oldincludedir = /usr/include
localedir = $(datarootdir)/locale
libdir = $(exec_prefix)/lib
mandir = $(datarootdir)/man
docdir = $(datarootdir)/doc/$(name)

